server:
  port: 8082 # Port for Borrowing Service

spring:
  application:
    name: borrowing-service # Name to register in Eureka
  datasource:
    url: jdbc:mysql://localhost:3306/borrowingDB
    username: root
    password: Athira_94
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # For development only; change for production
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
